import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flame_barrage/flame_barrage.dart';

class AssetLoadingScreen extends StatefulWidget {
  const AssetLoadingScreen({super.key});

  @override
  State<AssetLoadingScreen> createState() => _AssetLoadingScreenState();
}

class _AssetLoadingScreenState extends State<AssetLoadingScreen> {
  String _loadingStatus = 'Scanning asset directory...';
  bool _isLoading = true;
  bool _hasError = false;
  String _errorMessage = '';

  @override
  void initState() {
    super.initState();
    _startAutoPreloadPipeline();
  }

  Future<void> _startAutoPreloadPipeline() async {
    try {
      setState(() {
        _isLoading = true;
        _hasError = false;
        _loadingStatus = 'Scanning asset directory...';
      });

      final manifest = await AssetManifest.loadFromAssetBundle(rootBundle);
      final allAssetPaths = manifest.listAssets();

      final emojiPaths = allAssetPaths
          .where(
            (path) =>
                path.startsWith('assets/emoji/') &&
                (path.endsWith('.png') || path.endsWith('.jpg') || path.endsWith('.webp')),
          )
          .toList();

      if (emojiPaths.isEmpty) {
        throw Exception('No image assets found under assets/emoji/. Check the physical directory and the pubspec.yaml registration.');
      }

      final List<EmojiInfo> autoGeneratedEmojis = [];
      final len = emojiPaths.length;

      for (int i = 0; i < len; i++) {
        final path = emojiPaths[i];
        final fileName = path.split('/').last;
        final nameWithoutExtension = fileName.split('.').first;

        autoGeneratedEmojis.add(
          EmojiInfo(
            id: 'emoji_$nameWithoutExtension',
            keys: ['[$nameWithoutExtension]'],
            asset: path,
            width: 24.0,
            height: 24.0,
            sourceType: EmojiSourceType.asset,
          ),
        );
      }

      EmojiAtlas.instance.registerAll(autoGeneratedEmojis);

      setState(() {
        _loadingStatus = 'Decoding barrage textures (${autoGeneratedEmojis.length} total)...';
      });

      await EmojiAtlas.instance.preloadAll();

      setState(() {
        _loadingStatus = 'All barrage assets initialized successfully!';
        _isLoading = false;
      });

      await Future.delayed(const Duration(milliseconds: 300));

      if (mounted) {
        Navigator.pushReplacementNamed(context, '/');
      }
    } catch (e, stack) {
      BarrageLogger.e('AssetLoading', 'Automatic asset loading failed', e, stack);
      setState(() {
        _isLoading = false;
        _hasError = true;
        _errorMessage = e.toString();
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFF121212),
      body: Center(
        child: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 40.0),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              const Icon(Icons.folder_zip, size: 80, color: Colors.orangeAccent),
              const SizedBox(height: 40),
              if (_isLoading) ...[
                Text(
                  _loadingStatus,
                  style: const TextStyle(fontSize: 16, color: Colors.white70),
                  textAlign: TextAlign.center,
                ),
                const SizedBox(height: 24),
                const SizedBox(
                  width: 32,
                  height: 32,
                  child: CircularProgressIndicator(
                    valueColor: AlwaysStoppedAnimation<Color>(Colors.orangeAccent),
                    strokeWidth: 3,
                  ),
                ),
              ] else if (_hasError) ...[
                const Icon(Icons.error_outline, size: 48, color: Colors.redAccent),
                const SizedBox(height: 16),
                const Text(
                  'Automatic asset loading failed',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: Colors.redAccent),
                ),
                const SizedBox(height: 8),
                Text(
                  _errorMessage,
                  style: const TextStyle(fontSize: 12, color: Colors.grey),
                  textAlign: TextAlign.center,
                ),
                const SizedBox(height: 24),
                ElevatedButton.icon(
                  style: ElevatedButton.styleFrom(backgroundColor: Colors.white10),
                  onPressed: _startAutoPreloadPipeline,
                  icon: const Icon(Icons.refresh),
                  label: const Text('Rescan and load'),
                ),
              ] else ...[
                Text(
                  _loadingStatus,
                  style: const TextStyle(fontSize: 16, color: Colors.green),
                  textAlign: TextAlign.center,
                ),
              ],
            ],
          ),
        ),
      ),
    );
  }
}
